# Generated by Django 4.2.30 on 2026-05-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_verified_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mpesa_checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
